#!/bin/bash

root@ec3157dbd2e1:/alx-system_engineering-devops/0x00-shell_basics# ls -na                                                              
total 28                                                                                                                                
drwxr-xr-x 2 0 0  173 Feb  8 19:37 .                                                                                                    
drwxr-xr-x 4 0 0   60 Feb  8 14:11 ..                                                                                                   
-rwxr-xr-x 1 0 0   77 Feb  8 19:15 0-current_working_directory                                                                          
-rw-r--r-- 1 0 0   79 Feb  8 18:44 0x00-shell_basics                                                                                    
-rw-r--r-- 1 0 0   79 Feb  8 18:43 1                                                                                                    
-rw-r--r-- 1 0 0   40 Feb  8 18:45 1-listit                                                                                             
-rwxr--r-- 1 0 0   20 Feb  8 19:28 2-bring_me_home                                                                                      
-rw-r--r-- 1 0 0 1098 Feb  8 19:33 3-listfiles                                                                                          
-rw-r--r-- 1 0 0 1587 Feb  8 19:37 4-listmorefiles                                                                                      
-rw-r--r-- 1 0 0    0 Feb  8 17:55 README.md       
root@ec3157dbd2e1:/alx-system_engineering-devops/0x00-shell_basics#

